site_name: XtremeOwnage.com
site_author: XtremeOwnage
site_url: https://Static.XtremeOwnage.com/
site_description: Cars, Computer, and Code.

copyright: 'Copyright &copy; 2022 XtremeOwnage.com'

# repo_url: http://git.local.xtremeownage.com:3000/eric/XOSite.git
# repo_name: denysdovhan/smart-home

theme:
  name: material
  language: en
  logo: /assets/avatar/XO.png
  custom_dir: docs/overrides
  # icon:
  #   logo: material/home-assistant
  #   repo: fontawesome/brands/github
  font:
      text: "Open Sans"
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: grey
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    # - navigation.prune
    - navigation.indexes
    - toc.follow
    # - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    # - header.autohide

nav:
  - Home: index.md
  - Blog:
    - blog/index.md

plugins:
  - meta:
      meta_file: '**/.meta.yml' 
  - blog:
      blog_dir: blog/
      post_date_format: medium
      post_url_date_format: yyyy
      post_url_format: "{date}/{slug}"
      post_slugify_separator: "-"
      post_excerpt: required
      post_excerpt_max_categories: 5
      archive: true
      archive_date_format: MMM/yyyy
      archive_url_format: "archive/{date}"
      categories: true
      categories_name: Categories
      categories_url_format: "category/{slug}"
      categories_allowed:
        - Main
        - Development
        - Kubernetes
        - Home-Automation
      pagination: true
      pagination_per_page: 10
      pagination_url_format: "page/{page}"
      authors: true
      authors_file: "blog/.authors.yml"
  # - rss:
  #     enabled: true
  #     match_path: "blog.posts.*"
  #     date_from_meta:
  #       as_creation: date
  #     categories:
  #       - categories
  #       # - tags 
  - privacy:
      enabled: false
  - search:
      lang: en
  - tags:
      enabled: true
  - glightbox:  ## https://github.com/blueswen/mkdocs-glightbox#usage
      touchNavigation: true
      zoomable: true
markdown_extensions:
  - meta
  - toc:
      permalink: true
  - attr_list
  - admonition
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - footnotes
  - tables

extra_css:
  - stylesheets/extra.css

extra:
  # version:
  #   provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/XtremeOwnageDotCom
    - icon: fontawesome/brands/discord
      link: https://discord.gg/gncCn88
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/XtremeOwnage
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/denysdovhan
    - icon: fontawesome/solid/globe
      link: https://xtremeownage.com/
    - icon: fontawesome/solid/rss
      link: /feed_rss_created.xml
