site_name: XtremeOwnage.com
site_author: XtremeOwnage
site_url: https://Static.XtremeOwnage.com/
site_description: Cars, Computer, and Code.

copyright: 'Copyright &copy; 2025 XtremeOwnage.com'

# repo_url: http://git.local.xtremeownage.com:3000/eric/XOSite.git
# repo_name: denysdovhan/smart-home

theme:
  name: material
  language: en
  logo: /assets/avatar/XO.png
  custom_dir: docs/overrides
  # icon:
  #   logo: material/home-assistant
  #   repo: fontawesome/brands/github
  font:
      text: "Open Sans"
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: grey
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    # - navigation.prune
    - navigation.indexes
    - toc.follow
    # - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    # - header.autohide
    - content.footnote.tooltips
    - content.code.copy
    - content.code.select
    - content.code.annotate
nav:
  - Home: index.md
  - Projects: pages/Projects/index.md
  - Tags: pages/tags.md
  - Blog:
    - blog/index.md

plugins:
  - table-reader
  - meta:
      meta_file: .meta.yml
      enabled: true
  - blog:
      blog_dir: blog/
      post_date_format: medium
      post_url_date_format: yyyy
      post_url_format: "{date}/{slug}"
      post_slugify_separator: "-"
      post_excerpt: optional
      post_excerpt_max_categories: 5
      archive: true
      archive_date_format: yyyy
      archive_url_format: "archive/{date}"
      categories: true
      categories_name: Categories
      categories_url_format: "category/{slug}"
      categories_allowed:
        - Main
        - Development
        - Kubernetes
        - Home-Automation
        - Home-Improvement
        - Technology
        - Solar
      pagination: true
      pagination_per_page: 20
      pagination_url_format: "page/{page}"
      authors: true
      authors_file: "{blog}/.authors.yml"
  - rss:
      enabled: true
      match_path: "blog.posts.*"
      date_from_meta:
        as_creation: date
      categories:
        - categories
        # - tags 
  #- social: 
  #    enabled: false ## Needs special stuff for windows...
  # - optimize:
  #     enabled: true
  #     cache: true
  #     optimize_png: false
  #     optimize_png_strip: true
  #     optimize_jpg: true
  #- privacy:
  #    enabled: false
  #    cache: true
  #    links: false
  - search:
      lang: en
  - tags:
      enabled: true
      export: true
      listings: true
      tags_hierarchy: true          
  - glightbox:  ## https://github.com/blueswen/mkdocs-glightbox#usage
      touchNavigation: true
      zoomable: true
  # - redirects:
  #     redirect_maps:
  #       'discord': 'https://discord.gg/DcgPVwxaPz'
markdown_extensions:    # https://facelessuser.github.io/pymdown-extensions/extensions/tilde/
  - meta
  - toc:
      permalink: true
  - attr_list
  - admonition
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true 
  - footnotes
  - tables
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
extra_css:
  - stylesheets/extra.css

extra:
  # version:
  #   provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/XtremeOwnageDotCom
    - icon: fontawesome/brands/discord
      link: /discord
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/HTTP_404_NotFound
    - icon: fontawesome/solid/globe
      link: https://static.xtremeownage.com/
    - icon: fontawesome/solid/rss
      link: /feed_rss_created.xml
