name: build docs
on:
  push:
    branches:
      - master 
      - main
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11.x
      - run: pip install git+https://${{ secrets.GITHUB_TOKEN }}@github.com/XtremeOwnage/mkdocs-material-insiders.git
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force
